---
driver:
  name: docker

platforms:
  - name: fedora
    image: fedora:latest
    pre_build_image: true
    command: /usr/sbin/init
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible

verifier:
  name: ansible
